### ISSUE TITLE
Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by kvdmolen** [DemocracyOS/app#1004]
Error with fresh install (and after server-reboot): Cannot read property 'filter' of null:

```
democracyos:build Found error resolving dependencies tree TypeError: Cannot read property 'filter' of null +10s
TypeError: Cannot read property 'filter' of null
    at Function.maxSatisfying (/home/admin/app/node_modules/component-resolver/node_modules/semver/semver.js:951:18)
    at Resolver.<anonymous> (/home/admin/app/node_modules/component-resolver/build/semver.js:570:24)
    at Generator.invoke (/home/admin/app/node_modules/component-builder/build/index.js:141:31)
    at Generator.invoke (/home/admin/app/node_modules/component-builder/build/index.js:79:50)
    at next (/home/admin/app/node_modules/component-resolver/node_modules/co/index.js:74:21)
    at /home/admin/app/node_modules/component-resolver/node_modules/co/index.js:93:18
    at Gunzip.onEnd (/home/admin/app/node_modules/component-resolver/node_modules/component-remotes/node_modules/cogent/node_modules/raw-body/index.js:149:7)
    at Gunzip.g (events.js:199:16)
    at Gunzip.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

**Comment by mjlescano** [comment]
Couldn't reproduce the error neither on `master` or `development`. Looks like a dependency error from [component(1)](https://github.com/componentjs/component). Those are very common, more info: https://github.com/DemocracyOS/app/issues/927.

For now, try to run `make clean && npm cache clean && make`, and make sure that the build ends. You could also try something like [this retry](https://gist.github.com/mjlescano/d3cef76adaf9ad8448c0) command, and run `retry make` to make sure it ends correctly.

If you don't mind waiting, we're planning to launch `1.0.0` next week that doesn't use component :)
