### ISSUE TITLE
Dependency Error: timeago

### ISSUE THREAD

**Issue by kvdmolen** [DemocracyOS/app#1005]
Another error after a fresh install:

```
democracyos:build Found error resolving dependencies tree Error: no remote found for dependency "democracyos/timeago@master". run `component open troubleshooting` for help. +3s
Error: no remote found for dependency "democracyos/timeago@master". run `component open troubleshooting` for help.
    at Resolver.<anonymous> (/root/app/node_modules/component-resolver/build/dependencies.js:504:13)
    at Generator.invoke (/root/app/node_modules/component-builder/build/index.js:141:31)
    at Generator.invoke (/root/app/node_modules/component-builder/build/index.js:79:50)
    at next (/root/app/node_modules/component-resolver/node_modules/co/index.js:74:21)
    at /root/app/node_modules/component-resolver/node_modules/co/index.js:93:18
    at Gunzip.onEnd (/root/app/node_modules/component-resolver/node_modules/component-remotes/node_modules/cogent/node_modules/raw-body/index.js:149:7)
    at Gunzip.g (events.js:199:16)
    at Gunzip.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by kvdmolen** [comment]
Solved after server-reboot, but I leave it here for reference
