### ISSUE TITLE
Mongo sessions

### ISSUE THREAD

**Issue by slifszyc** [DemocracyOS/app#439]
Sometimes (randomly) there's an error on the sessions stored in mongo when using the application. Restarting the app may fix it but it shouldn't happen.

1. Catch that error and add it to this issue next time it occurs
2. Debug it and fix it

**Comment by gvilarino** [comment]
@jfresco I'm seeing this poping up again both in my development environment and production ones as well.

for instance, you can see the error in the [staging enviromnet](http://staging-democracyos.herokuapp.com/) (just do `heroku logs --app staging-democracyos`).

The log looks like this:

```
2015-01-09T02:54:20.597999+00:00 app[web.1]: Error: Error getting collection: sessions
2015-01-09T02:54:20.598020+00:00 app[web.1]:     at /app/node_modules/connect-mongo/lib/connect-mongo.js:160:19
2015-01-09T02:54:20.598024+00:00 app[web.1]:     at MongoStore._get_collection (/app/node_modules/connect-mongo/lib/connect-mongo.js:158:17)
2015-01-09T02:54:20.598026+00:00 app[web.1]:     at MongoStore.get (/app/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
2015-01-09T02:54:20.598023+00:00 app[web.1]:     at Db.collection (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:501:27)
2015-01-09T02:54:20.598036+00:00 app[web.1]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2015-01-09T02:54:20.598034+00:00 app[web.1]:     at Object.json [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/json.js:42:37)
2015-01-09T02:54:20.598028+00:00 app[web.1]:     at Object.session [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/session.js:311:11)
2015-01-09T02:54:20.598033+00:00 app[web.1]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2015-01-09T02:54:20.598029+00:00 app[web.1]:     at next (/app/node_modules/express/node_modules/connect/lib/proto.js:193:15)
2015-01-09T02:54:20.598031+00:00 app[web.1]:     at Object.cookieParser [as handle] (/app/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:65:5)
```

We need to fix this ASAP; we can't go ahead with a broken db connection.

**Comment by jfresco** [comment]
We removed the whole sessions feature by using JWT (see #579). Therefore, this error won't happen again. Closing.
