### ISSUE TITLE
Tag field in create laws form should be required

### ISSUE THREAD

**Issue by marcbc** [DemocracyOS/app#624]
This is and edge case, but the experience could be improved.

In a clean installation if you want to go ahead and create a new Law, you will have no tags in the Tag dropdown. Since the dropdown has no validation implemented, the creation request is sent to the back end and fails when trying to create the law, with no meaningful explanation in the UI. 

Through the app logs one can find out that...

```
/tmp/DemocracyOS/lib/db-api/tag.js:174
  if ('string' !== typeof tag.name) {
                             ^
TypeError: Cannot read property 'name' of undefined
    at Object.create (/tmp/DemocracyOS/lib/db-api/tag.js:174:30)
    at /tmp/DemocracyOS/lib/db-api/law.js:105:14
    at Promise.<anonymous> (/tmp/DemocracyOS/lib/db-api/tag.js:59:5)
    at Promise.<anonymous> (/tmp/DemocracyOS/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/tmp/DemocracyOS/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/tmp/DemocracyOS/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Object.cb (/tmp/DemocracyOS/node_modules/mongoose/lib/query.js:1010:22)
    at Object._onImmediate (/tmp/DemocracyOS/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

A solution could be making the field required (and improving the "required" validator, since it doesn't support undefined) that would trigger the error message before submitting the form.

**Comment by gvilarino** [comment]
This used to be a required field but we ended up making tags optional in the end. There must be some inconsistency with how data validation is being made.

**Comment by slifszyc** [comment]
`tag` is a required attribute for a `law`

See here: https://github.com/DemocracyOS/app/blob/master/lib/models/law.js#L76

**Comment by gvilarino** [comment]
But it seems there's no validation in the `admin` for this requirement. You could actually submit creation of a `law` with no `tag` and that would crash the server.
