### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by guillemcanal** [DemocracyOS/app#763]
I followed the installation guide. However, I cannot make DemocracyOS to work.

Linux Kernel:
 ```
Linux 3c3666c55097 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Distrib: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```
MongoDB:  `v2.4.9`
Node: `v0.10.38`
Npm: `1.4.28`
OpenSSL: `OpenSSL 1.0.1f 6 Jan 2014`

Result of `make` after loading democracyOS on port 80 in the browser

```bash
Installing dependencies...
npm WARN package.json co-prompt@1.0.0 No repository field.
npm WARN package.json t-component@1.0.0 repo should probably be repository.
npm WARN package.json type-component@0.0.1 No repository field.
npm WARN cannot run in wd DemocracyOS@0.14.0 node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build (wd=/usr/src/democracyos/app)
Starting application...
  democracyos:config Load local configuration from /usr/src/democracyos/app/config/development.json +0ms
  democracyos:config Merge environment set configuration variables +5ms
  democracyos:config Loaded config object for env development with sha "6324e10e8c1bdd9bc9d131b9caad283f" +3ms
  democracyos:config Invalid config key "mongoUsersUrl" +290ms
  democracyos:db Using mongodb hosts: localhost:27017 +34ms
  democracyos:db Using mongodb URI: mongodb://localhost:27017/DemocracyOS-dev +2ms
  democracyos:db Connecting to MongoDB database DemocracyOS-dev +4ms
  democracyos:root Application started on port 80 +2s
  democracyos:db Connected to MongoDB on URI: mongodb://localhost:27017/DemocracyOS-dev +17ms
  democracyos:db Connection to MongoDB is now OPEN on URI: mongodb://localhost:27017/DemocracyOS-dev +9ms
  democracyos:jwt HTTP header x-access-token has no token. Moving on... +8s
  democracyos:build Start assets compilation +506ms
  democracyos:build Start assets compilation +37ms
  outdated name of a dependency : please update: "component/get-document" -> "webmodules/get-document"
  outdated name of a dependency : please update: "component/get-document" -> "webmodules/get-document"
  outdated name of a dependency : please update: "tj/debug" -> "visionmedia/debug"
  outdated name of a dependency : please update: "tj/debug" -> "visionmedia/debug"
  democracyos:build Found error building scripts +45s
  democracyos:build Found error compiling assets: Error: failed to read "component~emitter@1.0.0"'s file "index.js" +9ms
Error: failed to read "component~emitter@1.0.0"'s file "index.js"
    at /usr/src/democracyos/app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
    at fs.js:208:20
    at OpenReq.Req.done (/usr/src/democracyos/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/src/democracyos/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/usr/src/democracyos/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/src/democracyos/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:108:15)
  democracyos:build Found error building styles: Error: failed to read "cristiandouce~loading-lock@0.0.2"'s file "loading-lock.css" +85ms
  democracyos:build Found error building scripts +13ms
  democracyos:build Found error compiling assets: Error: failed to read "component~emitter@1.0.0"'s file "index.js" +2ms
Error: failed to read "component~emitter@1.0.0"'s file "index.js"
    at /usr/src/democracyos/app/node_modules/component-builder/node_modules/component-manifest/build/index.js:440:21
    at fs.js:208:20
    at OpenReq.Req.done (/usr/src/democracyos/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/src/democracyos/app/node_modules/component-resolver/node_modules/graceful-fs/graceful-fs.js:63:22)
    at OpenReq.Req.done (/usr/src/democracyos/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/usr/src/democracyos/app/node_modules/component-builder/node_modules/graceful-fs/graceful-fs.js:63:22)
    at Object.oncomplete (fs.js:108:15)
  democracyos:build Found error building styles: Error: failed to read "cristiandouce~loading-lock@0.0.2"'s file "loading-lock.css" +11ms
  democracyos:build Files copied successfully +27ms
  democracyos:build Files copied successfully +1ms
```

**Comment by AaronNGray** [comment]
Possibly need to update to a later version of Ubuntu but I am not sure ?

Try an :-

    DEBUG=*
    make packages

And you should have more debug info available.

**Comment by AaronNGray** [comment]
What repo and branch are you using ?

**Comment by AaronNGray** [comment]
Any results ? If you paste the results of the 'make packages' with the
DEBUG=* I can determine what is wrong and if its an issue I flagged up.

**Comment by guillemcanal** [comment]
Hey, sorry for the delay.
I'm using the master branch, here is the result of  `make packages` with `DEBUG="*"`
Since the stdout is quite large, I pasted it on Pastebin: http://pastebin.com/JpA8LV9n

**Comment by guillemcanal** [comment]
Oh. I guess I understand what's going on here, I needed to use `--unsafe-perm` since I'm installing democracy-os with the root user, in fact, the project is running inside a docker container.

Still, I had errors:

```bash
npm ERR! DemocracyOS@0.14.0 postinstall: `node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DemocracyOS@0.14.0 postinstall script.
npm ERR! This is most likely a problem with the DemocracyOS package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/dos-install && node ./bin/dos-config && node ./bin/dos-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls DemocracyOS
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /usr/src/democracyos/app
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/src/democracyos/app/npm-debug.log
npm ERR! not ok code 0
```
Here is the content of `/usr/src/democracyos/app/npm-debug.log`: http://sprunge.us/OFFf

**Comment by guillemcanal** [comment]
Executing `npm owner ls DemocracyOS` gave me:

```bash
npm ERR! owner ls Couldn't get owner data DemocracyOS
npm ERR! 404 404 Not Found: DemocracyOS
npm ERR! 404 
npm ERR! 404 'DemocracyOS' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "DemocracyOS"
npm ERR! cwd /usr/src/democracyos/app
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/src/democracyos/app/npm-debug.log
npm ERR! not ok code 0
```

**Comment by guillemcanal** [comment]
Well, I narrowed down the issue to `dos-build`, The log is available here: http://sprunge.us/UQPH
I removed my password from the log file since it was available in plaintext ^^

**Comment by guillemcanal** [comment]
rerunning ./bin/dos-build gave me a more reliable error:

```bash
  component-resolver:locals resolved local "comments-replies-edit" +1ms
  component-resolver finished resolving locals +0ms
  democracyos:build Found error resolving dependencies tree Error: trouble finding dependency "slifszyc/user-agent@0.0.9". +1ms
[Error: trouble finding dependency "slifszyc/user-agent@0.0.9".]
  remotes:github:api used 0 +6ms
```

**Comment by AaronNGray** [comment]
I am not sure if this is the same problem that I was experiencing with
componentjs's component-install its seemed to have timing problems either a
race condition or retry problems. I found that if I worked at a time when
the internet was very quiet where the US and UK were I am were asleep I
could get a good install. I still have not really had the time to isolate
this problem as its in the componentjs installer code or related sub
modules. I found I had it working again so was not able to fix it. BUT I am
not sure if that is your problem.
https://github.com/DemocracyOS/app/issues/725 I also did PR's for
componentjs/component that are still open.

One thing that is needed if you have not done it that helps this problem is
setting your GITHUB_USERNAME and GITHUB_PASSWORD and/or setting up .netrc :-


https://github.com/componentjs/guide/blob/master/component/getting-started.md#configuring-github-access

I did find an oddity in the http://sprunge.us/UQPH dump file in
the component~emitter module name notice the tilde I am not sure where
that's loaded in it should be component-emitter.

You have installed :-

    On Ubuntu 14/13/lower, install the package node-legacy for NodeJS.

Also if it is an internet problem a straight :-

    component install --timeout 960000

can help some of the timing problems.

**Comment by guillemcanal** [comment]
Hey, I fact, the problem was simple: node shouldn't be run as the root user. 
Creating a specific user for nodejs fixed the problem.

Building a Dockerfile with Github credentials may be the last remaining issue here since CommonJS require authentication. So the idea is to build source first and then make an image out of it.

Thanks again for your help ;)

**Comment by mjlescano** [comment]
Any clarification we could add to the wiki so it doesn't happen to someone else?

**Comment by guillemcanal** [comment]
@mjlescano Except for "Node must not be run as root", not really ;)

**Comment by AaronNGray** [comment]
This is one technique I am planning on using, but have not tested fully
yet :-

    http://www.aarongray.org/Node.js/Node-instillation.txt

Aaron
